curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/overview.mdx" -o v2docs/overview.mdx || echo FAIL-v2-overview
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/migration.mdx" -o v2docs/migration.mdx || echo FAIL-v2-migration
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/initialization.mdx" -o v2docs/initialization.mdx || echo FAIL-v2-initialization
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/session-setup.mdx" -o v2docs/session-setup.mdx || echo FAIL-v2-session-setup
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/prompt-lifecycle.mdx" -o v2docs/prompt-lifecycle.mdx || echo FAIL-v2-prompt-lifecycle
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/content.mdx" -o v2docs/content.mdx || echo FAIL-v2-content
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/tool-calls.mdx" -o v2docs/tool-calls.mdx || echo FAIL-v2-tool-calls
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/extensibility.mdx" -o v2docs/extensibility.mdx || echo FAIL-v2-extensibility
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/schema.mdx" -o v2docs/schema.mdx || echo FAIL-v2-schema
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/authentication.mdx" -o v2docs/authentication.mdx || echo FAIL-v2-authentication
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/error.mdx" -o v2docs/error.mdx || echo FAIL-v2-error
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/elicitation.mdx" -o v2docs/elicitation.mdx || echo FAIL-v2-elicitation
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/cancellation.mdx" -o v2docs/cancellation.mdx || echo FAIL-v2-cancellation
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/session-config-options.mdx" -o v2docs/session-config-options.mdx || echo FAIL-v2-session-config-options
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/session-delete.mdx" -o v2docs/session-delete.mdx || echo FAIL-v2-session-delete
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/session-list.mdx" -o v2docs/session-list.mdx || echo FAIL-v2-session-list
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/slash-commands.mdx" -o v2docs/slash-commands.mdx || echo FAIL-v2-slash-commands
curl -sfL --max-time 25 "https://raw.githubusercontent.com/zed-industries/agent-client-protocol/main/docs/protocol/v2/transports.mdx" -o v2docs/transports.mdx || echo FAIL-v2-transports
